

dataset:
  bioproject: PRJNA1251496
  organism: Klebsiella pneumoniae
  genome_size: 5500000

transmission:
  snp_linked: 21        
  snp_unrelated: 50     

qc:
  min_base_quality: 20
  min_read_length_illumina: 50
  min_read_length_ont: 1000
  min_mean_depth: 30
  min_breadth_10x: 0.90
  min_mapping_rate: 0.80

resources:
  threads: 4  


reference:
  accession: GCA_050993895.1   # NCBI assembly of the earliest isolate (0326576)

snippy:
  mincov: 10      
  minfrac: 0.9    


ont:
  min_length: 500          
  min_mean_q: 90           
  target_bases: 550000000  
  clair3_model: r1041_e82_400bps_sup_v430_bacteria_finetuned
  assemble: ["6257373", "0327436-NDM"]   


pathogen_detection: report/tables/pathogen_detection_isolates.tsv